"""
hardware/config.py
──────────────────
Hardware-side configuration for the ESN State Classifier.

All values are read from environment variables (via .env) with sensible defaults,
making it easy to retrain the C-header target without changing source files.

Usage:
    from config import Config
    Config.ESN_N_RESERVOIR   # → 50
"""

import os
from pathlib import Path

try:
    from dotenv import load_dotenv
    load_dotenv(Path(__file__).parent / ".env")
except ImportError:
    pass  # python-dotenv optional; fall back to OS environment

# ── Resolved base directory (script-relative, CWD-independent) ─────────────
BASE_DIR = Path(__file__).parent.resolve()


class Config:
    """
    Central configuration for the hardware ESN classifier pipeline.

    The hardware ESN is a **3-input → 50-node reservoir → 3-class** classifier
    that maps (Voltage, Current, Temperature) → (Normal, Warning, Critical).

    This is intentionally decoupled from the software/visualiser ESN, which is
    a 4-input regression model (SOC/SOH estimation). Both sides share the same
    reservoir computing algorithm (leaky-integrator Echo State Network + Ridge
    Regression readout) but operate as fully independent pipelines.
    """

    # ── Dataset ────────────────────────────────────────────────────────────────
    # Path to the synthetic EV battery drive-cycle CSV generated by data_set.m
    CSV_PATH: str = str(
        BASE_DIR / os.getenv("CSV_FILE", "original_ev_battery_dataset_multiclass.csv")
    )

    # ── ESN Architecture ───────────────────────────────────────────────────────
    # Number of raw sensor inputs: [Voltage, Current, Temperature]
    ESN_N_INPUTS: int = int(os.getenv("ESN_N_INPUTS", "3"))

    # Hidden recurrent reservoir size. Larger → richer dynamics, more Flash usage.
    # 50 nodes gives ~85% sparsity → 375 NNZ (vs 2500 dense ops).  6.7× speedup.
    ESN_N_RESERVOIR: int = int(os.getenv("ESN_N_RESERVOIR", "50"))

    # Number of output classes: Normal (0), Warning (1), Critical (2)
    ESN_N_OUTPUTS: int = int(os.getenv("ESN_N_OUTPUTS", "3"))

    # ── ESN Hyperparameters ────────────────────────────────────────────────────
    # Spectral radius ρ controls memory horizon: ρ < 1 ensures echo-state property.
    # 0.95 gives long memory useful for slow thermal transients.
    ESN_SPECTRAL_RADIUS: float = float(os.getenv("ESN_SPECTRAL_RADIUS", "0.95"))

    # Leak rate α controls update speed. Lower → slower reservoir, more averaging.
    # 0.3 balances responsiveness to spikes vs. noise immunity.
    ESN_LEAK_RATE: float = float(os.getenv("ESN_LEAK_RATE", "0.3"))

    # Scales the magnitude of W_in. Larger → inputs dominate over reservoir dynamics.
    ESN_INPUT_SCALING: float = float(os.getenv("ESN_INPUT_SCALING", "1.0"))

    # L2 regularisation λ in Ridge Regression. Prevents over-fitting on short sequences.
    ESN_RIDGE_PARAM: float = float(os.getenv("ESN_RIDGE_PARAM", "1e-4"))

    # Fraction of W_res entries forced to zero. 0.85 → ~375 non-zeros in a 50×50 matrix.
    ESN_SPARSITY: float = float(os.getenv("ESN_SPARSITY", "0.85"))

    # Number of initial time-steps discarded so the reservoir settles from cold-start zeros.
    # Must be < number of training samples. 50 is sufficient for a 50-node reservoir.
    ESN_WASHOUT: int = int(os.getenv("ESN_WASHOUT", "50"))

    # ── Thermal Classification Thresholds (°C) ─────────────────────────────────
    # These match the thresholds encoded in data_set.m and the STM32 firmware output
    # labels. Change both here AND in data_set.m if you need different decision boundaries.
    TEMP_NORMAL_MAX: float = float(os.getenv("TEMP_NORMAL_MAX", "35.0"))   # < 35°C  → Normal (0)
    TEMP_WARNING_MAX: float = float(os.getenv("TEMP_WARNING_MAX", "45.0")) # 35–45°C → Warning (1)
    # ≥ 45°C → Critical (2)

    # ── Output ─────────────────────────────────────────────────────────────────
    # Path where train_classifier.py writes the generated C header
    WEIGHTS_HEADER: str = str(
        BASE_DIR / os.getenv("WEIGHTS_HEADER", "esn_classifier_weights.h")
    )
