/* Includes ------------------------------------------------------------------*/
#include "main.h"

/* Private includes ----------------------------------------------------------*/
/* USER CODE BEGIN Includes */
#include <stdio.h>
#include <stdint.h>
#include <math.h>
#include <time.h>

/*
 * ESN Architecture on this MCU:
 *
 *  Pipeline 1 — ESN CLASSIFIER (this file, active on STM32)
 *    weights  : esn_classifier_weights.h  (auto-generated by train_classifier.py)
 *    inputs   : [Voltage, Current, Temperature]   (3 features)
 *    reservoir: 50 nodes, spectral_radius=0.95, leak_rate=0.3
 *    outputs  : [Normal=0, Warning=1, Critical=2] (thermal safety class)
 *    inference: float32 + Q15 fixed-point side-by-side for validation
 *
 *  Pipeline 2 — ESN ESTIMATOR (software-only, NOT included here)
 *    weights  : esn_estimator_weights.h  (generated by train_estimator.py)
 *    inputs   : [Voltage, Current, Voltage_grad, Current_ma]  (4 features)
 *    reservoir: SOC=500 nodes, SOH=400 nodes
 *    outputs  : SOC (float 0-1), SOH (float 0-1)
 *    NOTE: Dense W_res at 500 nodes = 1 MB RAM — exceeds STM32F4 SRAM budget.
 *          SOC/SOH estimation runs on the Python visualiser instead.
 *          Hardware-side cross-validation is done offline via train_estimator.py.
 */
#include "esn_classifier_weights.h"
#include "esn_estimator_weights.h"
/* USER CODE END Includes */

/* Private typedef -----------------------------------------------------------*/
/* USER CODE BEGIN PTD */

/* USER CODE END PTD */

/* Private define ------------------------------------------------------------*/
/* USER CODE BEGIN PD */

/* USER CODE END PD */

/* Private macro -------------------------------------------------------------*/
/* USER CODE BEGIN PM */

/* USER CODE END PM */



UART_HandleTypeDef huart2;

/* USER CODE BEGIN PV */
#define EVALUATION_SAMPLES_COUNT 500
#define N EVALUATION_SAMPLES_COUNT // Evaluation dataset sample count for host simulation benchmark loop
#define ESN_FIXED_POINT 0 // Set to 1 to enable Q15 Fixed-Point ESN Inference

// Reservoir states
float esn_x[ESN_N_RESERVOIR] = {0.0f};
int16_t esn_x_q[ESN_N_RESERVOIR] = {0};

// Helper function to scale float to Q15
int16_t float_to_q15(float v) {
    float temp = v * 32768.0f;
    if (temp >= 32767.0f) return 32767;
    if (temp <= -32768.0f) return -32768;
    return (int16_t)temp;
}

// Helper function to scale float to Q12
int16_t float_to_q12(float v) {
    float temp = v * 4096.0f;
    if (temp >= 32767.0f) return 32767;
    if (temp <= -32768.0f) return -32768;
    return (int16_t)temp;
}

// Pre-quantized arrays for high-performance fixed-point execution
int16_t tanh_lut[33];
int16_t esn_W_in_q15[ESN_N_RESERVOIR][1 + ESN_N_INPUTS];
int16_t esn_W_res_val_q15[ESN_W_RES_NNZ];
int16_t leak_rate_q15;
int16_t one_minus_leak_rate_q15;

// Initialise lookup table for high-speed integer activation (covers 0.0 to 8.0 in steps of 0.25)
void init_tanh_lut(void) {
    for (int i = 0; i <= 32; i++) {
        float x = (float)i * 0.25f;
        float y = tanhf(x);
        tanh_lut[i] = float_to_q15(y);
    }
}

// Initialise weights into Q15 format at startup to avoid runtime float ops
void init_fixed_point_weights(void) {
    leak_rate_q15 = float_to_q15(ESN_LEAK_RATE);
    one_minus_leak_rate_q15 = float_to_q15(1.0f - ESN_LEAK_RATE);
    for (int i = 0; i < ESN_N_RESERVOIR; i++) {
        for (int j = 0; j < 1 + ESN_N_INPUTS; j++) {
            esn_W_in_q15[i][j] = float_to_q15(esn_W_in[i][j]);
        }
    }
    for (int i = 0; i < ESN_W_RES_NNZ; i++) {
        esn_W_res_val_q15[i] = float_to_q15(esn_W_res_val[i]);
    }
}

// Tanh activation function in Q15 precision using LUT linear interpolation.
// Input (x_q12) is in Q12 format (representing -8.0 to +8.0), output is in Q15 format.
// Safe against integer overflow and out-of-bounds lookups.
int16_t q15_tanh(int16_t x_q12) {
    if (x_q12 == -32768) x_q12 = -32767;
    int16_t abs_x = x_q12 < 0 ? -x_q12 : x_q12;
    if (abs_x > 32767) abs_x = 32767; // safety clamp
    
    int idx = abs_x >> 10; // 0 to 31 (since 32767 >> 10 is 31)
    if (idx > 31) idx = 31; // defensive array bounds guard
    
    int frac = abs_x & 1023;
    int32_t y = ((1024 - frac) * (int32_t)tanh_lut[idx] + frac * (int32_t)tanh_lut[idx + 1]) >> 10;
    return x_q12 < 0 ? -((int16_t)y) : (int16_t)y;
}

// Perform ESN prediction step in float32 (with CSR optimization)
void esn_predict_float(const float u[ESN_N_INPUTS], float y_pred[ESN_N_OUTPUTS]) {
    // 1. Scale inputs using means and standard deviations
    float u_scaled[ESN_N_INPUTS];
    for (int i = 0; i < ESN_N_INPUTS; i++) {
        float std_val = esn_input_stds[i] > 1e-6f ? esn_input_stds[i] : 1.0f;
        u_scaled[i] = (u[i] - esn_input_means[i]) / std_val;
    }

    // 2. Update reservoir states using CSR Sparse Matrix Multiplication
    float arg[ESN_N_RESERVOIR];
    for (int i = 0; i < ESN_N_RESERVOIR; i++) {
        // Bias + input multiplication
        float sum = esn_W_in[i][0] * 1.0f; // Bias input is 1.0f
        for (int j = 0; j < ESN_N_INPUTS; j++) {
            sum += esn_W_in[i][1 + j] * u_scaled[j];
        }

        // Sparse reservoir matrix multiplication (SpMV via CSR)
        uint16_t start = esn_W_res_row_ptr[i];
        uint16_t end = esn_W_res_row_ptr[i + 1];
        for (uint16_t k = start; k < end; k++) {
            uint16_t col_idx = esn_W_res_col[k];
            sum += esn_W_res_val[k] * esn_x[col_idx];
        }
        arg[i] = sum;
    }

    // 3. Apply leak rate and tanh activation
    for (int i = 0; i < ESN_N_RESERVOIR; i++) {
        esn_x[i] = (1.0f - ESN_LEAK_RATE) * esn_x[i] + ESN_LEAK_RATE * tanhf(arg[i]);
    }

    // 4. Compute output: y_pred = W_out * [1.0, u_scaled, esn_x]
    for (int i = 0; i < ESN_N_OUTPUTS; i++) {
        float sum = esn_W_out[i][0] * 1.0f; // Bias
        for (int j = 0; j < ESN_N_INPUTS; j++) {
            sum += esn_W_out[i][1 + j] * u_scaled[j];
        }
        for (int j = 0; j < ESN_N_RESERVOIR; j++) {
            sum += esn_W_out[i][1 + ESN_N_INPUTS + j] * esn_x[j];
        }
        if (sum < 0.0f) sum = 0.0f;
        if (sum > 1.0f) sum = 1.0f;
        y_pred[i] = sum;
    }
}

// Perform ESN prediction step in Q15 fixed-point (with CSR optimization, pure integer path)
void esn_predict_fixed(const float u[ESN_N_INPUTS], float y_pred[ESN_N_OUTPUTS]) {
    // 1. Scale inputs and convert to Q12 format (range +/- 8.0)
    int16_t u_scaled_q12[ESN_N_INPUTS];
    for (int i = 0; i < ESN_N_INPUTS; i++) {
        float std_val = esn_input_stds[i] > 1e-6f ? esn_input_stds[i] : 1.0f;
        float val = (u[i] - esn_input_means[i]) / std_val;
        u_scaled_q12[i] = float_to_q12(val);
    }

    // 2. Update reservoir states using CSR (sum calculated in Q12 format to allow arg range up to +/- 8.0)
    int16_t arg_q12[ESN_N_RESERVOIR];
    for (int i = 0; i < ESN_N_RESERVOIR; i++) {
        // Bias term: W_in_q15[i][0] is in Q15. Bias input is 1.0.
        // (Q15 * 1.0) in Q12 is (W_in_q15[i][0] * 4096) >> 15 = W_in_q15[i][0] >> 3
        int32_t sum = ((int32_t)esn_W_in_q15[i][0]) >> 3;

        // Input terms: W_in_q15[i][1+j] is in Q15, u_scaled_q12 is in Q12
        // (Q15 * Q12) >> 15 = Q12
        for (int j = 0; j < ESN_N_INPUTS; j++) {
            sum += ((int32_t)esn_W_in_q15[i][1 + j] * u_scaled_q12[j]) >> 15;
        }

        // Reservoir terms: W_res is in Q15, esn_x_q is in Q15
        // (Q15 * Q15) >> 18 = Q12
        uint16_t start = esn_W_res_row_ptr[i];
        uint16_t end = esn_W_res_row_ptr[i + 1];
        for (uint16_t k = start; k < end; k++) {
            uint16_t col_idx = esn_W_res_col[k];
            sum += ((int32_t)esn_W_res_val_q15[k] * esn_x_q[col_idx]) >> 18;
        }
        
        // Clip to avoid overflow of 16-bit signed integer (Q12 limit +/- 8.0)
        if (sum > 32767) sum = 32767;
        if (sum < -32768) sum = -32768;
        arg_q12[i] = (int16_t)sum;
    }

    // 3. Apply leak rate and tanh activation:
    // x_q(t) = (1 - alpha) * x_q(t-1) + alpha * tanh(arg_q12)

    for (int i = 0; i < ESN_N_RESERVOIR; i++) {
        // arg_q12[i] is in Q12, which represents up to 8.0 and q15_tanh expects Q12 input!
        int16_t tanh_val = q15_tanh(arg_q12[i]);
        int32_t state_update = ((int32_t)one_minus_leak_rate_q15 * esn_x_q[i]) >> 15;
        state_update += ((int32_t)leak_rate_q15 * tanh_val) >> 15;
        
        if (state_update > 32767) state_update = 32767;
        if (state_update < -32768) state_update = -32768;
        esn_x_q[i] = (int16_t)state_update;
    }

    // 4. Compute output: y_pred = W_out * [1.0, u_scaled, esn_x_q] (Readout in float)
    for (int i = 0; i < ESN_N_OUTPUTS; i++) {
        float sum = esn_W_out[i][0] * 1.0f; // Bias
        for (int j = 0; j < ESN_N_INPUTS; j++) {
            float val = (u[j] - esn_input_means[j]) / esn_input_stds[j];
            sum += esn_W_out[i][1 + j] * val;
        }
        for (int j = 0; j < ESN_N_RESERVOIR; j++) {
            float state_f = (float)esn_x_q[j] / 32768.0f;
            sum += esn_W_out[i][1 + ESN_N_INPUTS + j] * state_f;
        }
        if (sum < 0.0f) sum = 0.0f;
        if (sum > 1.0f) sum = 1.0f;
        y_pred[i] = sum;
    }
}

// ── ESN Estimator Reservoir States & Prediction Functions ──────────────────────
float esn_soc_x[ESN_SOC_N_RESERVOIR] = {0.0f};
float esn_soh_x[ESN_SOH_N_RESERVOIR] = {0.0f};

// Perform ESN SOC prediction step (4 features -> SOC float 0..1)
float esn_predict_soc(const float u[ESN_ESTIMATOR_N_INPUTS]) {
    // 1. Scale inputs
    float u_scaled[ESN_ESTIMATOR_N_INPUTS];
    for (int i = 0; i < ESN_ESTIMATOR_N_INPUTS; i++) {
        u_scaled[i] = (u[i] - esn_estimator_input_means[i]) / esn_estimator_input_stds[i];
    }
    // 2. Update reservoir states using CSR Sparse Matrix Multiplication
    float arg[ESN_SOC_N_RESERVOIR];
    for (int i = 0; i < ESN_SOC_N_RESERVOIR; i++) {
        float sum = esn_soc_W_in[i][0] * 1.0f; // Bias
        for (int j = 0; j < ESN_ESTIMATOR_N_INPUTS; j++) {
            sum += esn_soc_W_in[i][1 + j] * u_scaled[j];
        }
        uint16_t start = esn_soc_W_res_row_ptr[i];
        uint16_t end = esn_soc_W_res_row_ptr[i + 1];
        for (uint16_t k = start; k < end; k++) {
            uint16_t col_idx = esn_soc_W_res_col[k];
            sum += esn_soc_W_res_val[k] * esn_soc_x[col_idx];
        }
        arg[i] = sum;
    }
    // 3. Apply leak rate & tanh
    for (int i = 0; i < ESN_SOC_N_RESERVOIR; i++) {
        esn_soc_x[i] = (1.0f - ESN_SOC_LEAK_RATE) * esn_soc_x[i] + ESN_SOC_LEAK_RATE * tanhf(arg[i]);
    }
    // 4. Output: y_pred = W_out * [1.0, u_scaled, esn_soc_x]
    float soc_pred = esn_soc_W_out[0][0] * 1.0f;
    for (int j = 0; j < ESN_ESTIMATOR_N_INPUTS; j++) {
        soc_pred += esn_soc_W_out[0][1 + j] * u_scaled[j];
    }
    for (int j = 0; j < ESN_SOC_N_RESERVOIR; j++) {
        soc_pred += esn_soc_W_out[0][1 + ESN_ESTIMATOR_N_INPUTS + j] * esn_soc_x[j];
    }
    if (soc_pred < 0.0f) soc_pred = 0.0f;
    if (soc_pred > 1.0f) soc_pred = 1.0f;
    return soc_pred;
}

// Perform ESN SOH prediction step (4 features -> SOH float 0..1)
float esn_predict_soh(const float u[ESN_ESTIMATOR_N_INPUTS]) {
    // 1. Scale inputs
    float u_scaled[ESN_ESTIMATOR_N_INPUTS];
    for (int i = 0; i < ESN_ESTIMATOR_N_INPUTS; i++) {
        u_scaled[i] = (u[i] - esn_estimator_input_means[i]) / esn_estimator_input_stds[i];
    }
    // 2. Update reservoir states using CSR Sparse Matrix Multiplication
    float arg[ESN_SOH_N_RESERVOIR];
    for (int i = 0; i < ESN_SOH_N_RESERVOIR; i++) {
        float sum = esn_soh_W_in[i][0] * 1.0f; // Bias
        for (int j = 0; j < ESN_ESTIMATOR_N_INPUTS; j++) {
            sum += esn_soh_W_in[i][1 + j] * u_scaled[j];
        }
        uint16_t start = esn_soh_W_res_row_ptr[i];
        uint16_t end = esn_soh_W_res_row_ptr[i + 1];
        for (uint16_t k = start; k < end; k++) {
            uint16_t col_idx = esn_soh_W_res_col[k];
            sum += esn_soh_W_res_val[k] * esn_soh_x[col_idx];
        }
        arg[i] = sum;
    }
    // 3. Apply leak rate & tanh
    for (int i = 0; i < ESN_SOH_N_RESERVOIR; i++) {
        esn_soh_x[i] = (1.0f - ESN_SOH_LEAK_RATE) * esn_soh_x[i] + ESN_SOH_LEAK_RATE * tanhf(arg[i]);
    }
    // 4. Output: y_pred = W_out * [1.0, u_scaled, esn_soh_x]
    float soh_pred = esn_soh_W_out[0][0] * 1.0f;
    for (int j = 0; j < ESN_ESTIMATOR_N_INPUTS; j++) {
        soh_pred += esn_soh_W_out[0][1 + j] * u_scaled[j];
    }
    for (int j = 0; j < ESN_SOH_N_RESERVOIR; j++) {
        soh_pred += esn_soh_W_out[0][1 + ESN_ESTIMATOR_N_INPUTS + j] * esn_soh_x[j];
    }
    if (soh_pred < 0.0f) soh_pred = 0.0f;
    if (soh_pred > 1.0f) soh_pred = 1.0f;
    return soh_pred;
}

float data[500][4] = {
  {11.620f, 2.311f, 32.541f, 0},
  {11.607f, 2.420f, 32.544f, 0},
  {11.608f, 2.377f, 32.547f, 0},
  {11.606f, 2.367f, 32.550f, 0},
  {11.596f, 2.448f, 32.553f, 0},
  {11.596f, 2.410f, 32.555f, 0},
  {11.588f, 2.461f, 32.558f, 0},
  {11.586f, 2.441f, 32.561f, 0},
  {11.591f, 2.347f, 32.563f, 0},
  {11.587f, 2.361f, 32.566f, 0},
  {11.578f, 2.436f, 32.568f, 0},
  {11.582f, 2.353f, 32.571f, 0},
  {11.578f, 2.370f, 32.573f, 0},
  {11.577f, 2.351f, 32.576f, 0},
  {11.570f, 2.395f, 32.578f, 0},
  {11.564f, 2.429f, 32.580f, 0},
  {11.568f, 2.345f, 32.583f, 0},
  {11.565f, 2.352f, 32.585f, 0},
  {11.555f, 2.426f, 32.588f, 0},
  {11.548f, 2.465f, 32.590f, 0},
  {11.548f, 2.429f, 32.593f, 0},
  {11.555f, 2.315f, 32.595f, 0},
  {11.547f, 2.383f, 32.598f, 0},
  {11.542f, 2.404f, 32.600f, 0},
  {11.539f, 2.395f, 32.603f, 0},
  {11.539f, 2.368f, 32.605f, 0},
  {11.541f, 2.311f, 32.608f, 0},
  {11.525f, 2.463f, 32.611f, 0},
  {11.522f, 2.460f, 32.614f, 0},
  {11.519f, 2.447f, 32.617f, 0},
  {11.520f, 2.397f, 32.620f, 0},
  {11.521f, 2.355f, 32.623f, 0},
  {11.509f, 2.456f, 32.626f, 0},
  {11.512f, 2.390f, 32.629f, 0},
  {11.506f, 2.427f, 32.633f, 0},
  {11.495f, 2.509f, 32.636f, 0},
  {11.492f, 2.502f, 32.640f, 0},
  {11.493f, 2.445f, 32.644f, 0},
  {11.486f, 2.488f, 32.648f, 0},
  {11.487f, 2.445f, 32.652f, 0},
  {11.484f, 2.449f, 32.657f, 0},
  {11.477f, 2.488f, 32.661f, 0},
  {11.478f, 2.444f, 32.666f, 0},
  {11.459f, 2.613f, 32.671f, 0},
  {11.460f, 2.555f, 32.677f, 0},
  {11.461f, 2.504f, 32.682f, 0},
  {11.453f, 2.554f, 32.688f, 0},
  {11.444f, 2.616f, 32.694f, 0},
  {11.444f, 2.573f, 32.700f, 0},
  {11.440f, 2.585f, 32.707f, 0},
  {11.430f, 2.650f, 32.714f, 0},
  {11.422f, 2.701f, 32.721f, 0},
  {11.419f, 2.687f, 32.729f, 0},
  {11.417f, 2.667f, 32.737f, 0},
  {11.410f, 2.704f, 32.746f, 0},
  {11.406f, 2.697f, 32.755f, 0},
  {11.403f, 2.693f, 32.764f, 0},
  {11.398f, 2.702f, 32.774f, 0},
  {11.394f, 2.717f, 32.784f, 0},
  {11.388f, 2.735f, 32.795f, 0},
  {11.379f, 2.800f, 32.806f, 0},
  {11.379f, 2.743f, 32.818f, 0},
  {11.367f, 2.839f, 32.830f, 0},
  {11.367f, 2.795f, 32.843f, 0},
  {11.355f, 2.882f, 32.856f, 0},
  {11.352f, 2.875f, 32.871f, 0},
  {11.341f, 2.955f, 32.885f, 0},
  {11.331f, 3.024f, 32.901f, 0},
  {11.335f, 2.920f, 32.917f, 0},
  {11.325f, 2.996f, 32.934f, 0},
  {11.318f, 3.025f, 32.951f, 0},
  {11.310f, 3.071f, 32.970f, 0},
  {11.302f, 3.115f, 32.989f, 0},
  {11.298f, 3.111f, 33.009f, 0},
  {11.288f, 3.177f, 33.029f, 0},
  {11.275f, 3.274f, 33.051f, 0},
  {11.270f, 3.266f, 33.074f, 0},
  {11.266f, 3.269f, 33.097f, 0},
  {11.254f, 3.345f, 33.122f, 0},
  {11.245f, 3.393f, 33.147f, 0},
  {11.247f, 3.315f, 33.174f, 0},
  {11.233f, 3.433f, 33.201f, 0},
  {11.215f, 3.579f, 33.230f, 0},
  {11.214f, 3.522f, 33.259f, 0},
  {11.205f, 3.568f, 33.290f, 0},
  {11.190f, 3.678f, 33.322f, 0},
  {11.193f, 3.580f, 33.355f, 0},
  {11.176f, 3.724f, 33.389f, 0},
  {11.172f, 3.708f, 33.424f, 0},
  {11.161f, 3.778f, 33.461f, 0},
  {11.150f, 3.839f, 33.499f, 0},
  {11.144f, 3.841f, 33.538f, 0},
  {11.137f, 3.863f, 33.579f, 0},
  {11.123f, 3.971f, 33.620f, 0},
  {11.116f, 3.977f, 33.664f, 0},
  {11.106f, 4.033f, 33.708f, 0},
  {11.094f, 4.102f, 33.754f, 0},
  {11.083f, 4.161f, 33.801f, 0},
  {11.078f, 4.149f, 33.850f, 0},
  {11.072f, 4.157f, 33.900f, 0},
  {11.057f, 4.272f, 33.951f, 0},
  {11.043f, 4.362f, 34.004f, 0},
  {11.041f, 4.310f, 34.058f, 0},
  {11.027f, 4.411f, 34.113f, 0},
  {11.013f, 4.501f, 34.170f, 0},
  {11.009f, 4.471f, 34.229f, 0},
  {10.998f, 4.536f, 34.289f, 0},
  {10.990f, 4.558f, 34.350f, 0},
  {10.983f, 4.561f, 34.413f, 0},
  {10.973f, 4.611f, 34.477f, 0},
  {10.966f, 4.633f, 34.542f, 0},
  {10.952f, 4.729f, 34.609f, 0},
  {10.933f, 4.870f, 34.677f, 0},
  {10.929f, 4.834f, 34.747f, 0},
  {10.914f, 4.945f, 34.817f, 0},
  {10.914f, 4.860f, 34.889f, 0},
  {10.903f, 4.921f, 34.963f, 0},
  {10.884f, 5.073f, 35.038f, 1},
  {10.887f, 4.958f, 35.113f, 1},
  {10.880f, 4.999f, 35.191f, 1},
  {10.859f, 5.203f, 35.269f, 1},
  {10.855f, 5.190f, 35.348f, 1},
  {10.851f, 5.190f, 35.429f, 1},
  {10.844f, 5.218f, 35.511f, 1},
  {10.833f, 5.307f, 35.593f, 1},
  {10.827f, 5.319f, 35.677f, 1},
  {10.820f, 5.358f, 35.762f, 1},
  {10.810f, 5.426f, 35.848f, 1},
  {10.803f, 5.452f, 35.934f, 1},
  {10.801f, 5.432f, 36.022f, 1},
  {10.801f, 5.385f, 36.110f, 1},
  {10.783f, 5.552f, 36.200f, 1},
  {10.786f, 5.464f, 36.290f, 1},
  {10.787f, 5.419f, 36.380f, 1},
  {10.769f, 5.592f, 36.472f, 1},
  {10.763f, 5.609f, 36.564f, 1},
  {10.760f, 5.599f, 36.657f, 1},
  {10.751f, 5.663f, 36.750f, 1},
  {10.739f, 5.751f, 36.844f, 1},
  {10.737f, 5.725f, 36.938f, 1},
  {10.734f, 5.718f, 37.033f, 1},
  {10.726f, 5.762f, 37.129f, 1},
  {10.728f, 5.698f, 37.225f, 1},
  {10.722f, 5.729f, 37.321f, 1},
  {10.715f, 5.772f, 37.417f, 1},
  {10.709f, 5.790f, 37.514f, 1},
  {10.690f, 5.979f, 37.611f, 1},
  {10.690f, 5.918f, 37.708f, 1},
  {10.683f, 5.959f, 37.806f, 1},
  {10.682f, 5.914f, 37.904f, 1},
  {10.679f, 5.911f, 38.001f, 1},
  {10.668f, 6.005f, 38.099f, 1},
  {10.664f, 6.004f, 38.197f, 1},
  {10.662f, 5.979f, 38.295f, 1},
  {10.662f, 5.927f, 38.393f, 1},
  {10.642f, 6.138f, 38.491f, 1},
  {10.637f, 6.150f, 38.590f, 1},
  {10.645f, 6.010f, 38.687f, 1},
  {10.632f, 6.141f, 38.785f, 1},
  {10.633f, 6.078f, 38.883f, 1},
  {10.631f, 6.076f, 38.981f, 1},
  {10.629f, 6.068f, 39.078f, 1},
  {10.623f, 6.110f, 39.176f, 1},
  {10.617f, 6.154f, 39.273f, 1},
  {10.619f, 6.087f, 39.370f, 1},
  {10.609f, 6.176f, 39.466f, 1},
  {10.612f, 6.105f, 39.563f, 1},
  {10.603f, 6.184f, 39.659f, 1},
  {10.603f, 6.156f, 39.755f, 1},
  {10.590f, 6.277f, 39.850f, 1},
  {10.594f, 6.189f, 39.945f, 1},
  {10.588f, 6.223f, 40.040f, 1},
  {10.582f, 6.266f, 40.135f, 1},
  {10.581f, 6.243f, 40.229f, 1},
  {10.579f, 6.234f, 40.323f, 1},
  {10.580f, 6.183f, 40.416f, 1},
  {10.571f, 6.261f, 40.509f, 1},
  {10.562f, 6.346f, 40.602f, 1},
  {10.561f, 6.318f, 40.694f, 1},
  {10.563f, 6.247f, 40.786f, 1},
  {10.552f, 6.361f, 40.878f, 1},
  {10.552f, 6.314f, 40.969f, 1},
  {10.545f, 6.365f, 41.059f, 1},
  {10.544f, 6.343f, 41.149f, 1},
  {10.550f, 6.226f, 41.239f, 1},
  {10.542f, 6.296f, 41.328f, 1},
  {10.529f, 6.436f, 41.417f, 1},
  {10.532f, 6.353f, 41.505f, 1},
  {10.530f, 6.339f, 41.593f, 1},
  {10.523f, 6.389f, 41.680f, 1},
  {10.518f, 6.411f, 41.767f, 1},
  {10.519f, 6.352f, 41.853f, 1},
  {10.511f, 6.410f, 41.939f, 1},
  {10.513f, 6.337f, 42.025f, 1},
  {10.506f, 6.372f, 42.110f, 1},
  {10.502f, 6.381f, 42.194f, 1},
  {10.495f, 6.427f, 42.278f, 1},
  {10.483f, 6.519f, 42.362f, 1},
  {10.484f, 6.459f, 42.445f, 1},
  {10.485f, 6.389f, 42.527f, 1},
  {10.484f, 6.356f, 42.610f, 1},
  {10.477f, 6.406f, 42.691f, 1},
  {10.464f, 6.525f, 42.772f, 1},
  {10.463f, 6.482f, 42.853f, 1},
  {10.464f, 6.407f, 42.933f, 1},
  {10.451f, 6.533f, 43.013f, 1},
  {10.455f, 6.429f, 43.092f, 1},
  {10.448f, 6.475f, 43.171f, 1},
  {10.446f, 6.447f, 43.249f, 1},
  {10.439f, 6.486f, 43.327f, 1},
  {10.437f, 6.458f, 43.405f, 1},
  {10.433f, 6.460f, 43.482f, 1},
  {10.429f, 6.465f, 43.558f, 1},
  {10.414f, 6.609f, 43.635f, 1},
  {10.425f, 6.412f, 43.710f, 1},
  {10.409f, 6.568f, 43.786f, 1},
  {10.410f, 6.499f, 43.860f, 1},
  {10.402f, 6.555f, 43.935f, 1},
  {10.396f, 6.584f, 44.009f, 1},
  {10.401f, 6.464f, 44.082f, 1},
  {10.388f, 6.579f, 44.156f, 1},
  {10.387f, 6.534f, 44.228f, 1},
  {10.386f, 6.500f, 44.301f, 1},
  {10.377f, 6.555f, 44.373f, 1},
  {10.370f, 6.557f, 44.444f, 1},
  {10.361f, 6.582f, 44.516f, 1},
  {10.354f, 6.592f, 44.586f, 1},
  {10.349f, 6.562f, 44.657f, 1},
  {10.338f, 6.620f, 44.727f, 1},
  {10.332f, 6.603f, 44.797f, 1},
  {10.321f, 6.656f, 44.866f, 1},
  {10.313f, 6.669f, 44.935f, 1},
  {10.312f, 6.578f, 45.004f, 2},
  {10.304f, 6.594f, 45.072f, 2},
  {10.292f, 6.666f, 45.140f, 2},
  {10.281f, 6.720f, 45.208f, 2},
  {10.276f, 6.688f, 45.275f, 2},
  {10.273f, 6.629f, 45.342f, 2},
  {10.265f, 6.644f, 45.409f, 2},
  {10.253f, 6.720f, 45.475f, 2},
  {10.255f, 6.588f, 45.541f, 2},
  {10.245f, 6.638f, 45.607f, 2},
  {10.240f, 6.616f, 45.672f, 2},
  {10.225f, 6.731f, 45.737f, 2},
  {10.227f, 6.604f, 45.802f, 2},
  {10.217f, 6.645f, 45.867f, 2},
  {10.208f, 6.680f, 45.931f, 2},
  {10.199f, 6.699f, 45.995f, 2},
  {10.194f, 6.668f, 46.059f, 2},
  {10.189f, 6.643f, 46.122f, 2},
  {10.179f, 6.683f, 46.186f, 2},
  {10.172f, 6.689f, 46.249f, 2},
  {10.168f, 6.651f, 46.311f, 2},
  {10.161f, 6.649f, 46.374f, 2},
  {10.148f, 6.732f, 46.436f, 2},
  {10.136f, 6.762f, 46.498f, 2},
  {10.122f, 6.760f, 46.560f, 2},
  {10.109f, 6.739f, 46.622f, 2},
  {10.097f, 6.713f, 46.683f, 2},
  {10.087f, 6.668f, 46.744f, 2},
  {10.071f, 6.706f, 46.805f, 2},
  {10.055f, 6.731f, 46.866f, 2},
  {10.040f, 6.753f, 46.926f, 2},
  {10.024f, 6.786f, 46.987f, 2},
  {10.009f, 6.791f, 47.047f, 2},
  {9.992f, 6.827f, 47.107f, 2},
  {9.979f, 6.809f, 47.166f, 2},
  {9.971f, 6.728f, 47.226f, 2},
  {9.949f, 6.843f, 47.285f, 2},
  {9.941f, 6.756f, 47.344f, 2},
  {9.925f, 6.792f, 47.404f, 2},
  {9.912f, 6.785f, 47.462f, 2},
  {9.892f, 6.859f, 47.521f, 2},
  {9.886f, 6.745f, 47.580f, 2},
  {9.864f, 6.869f, 47.638f, 2},
  {9.854f, 6.808f, 47.696f, 2},
  {9.840f, 6.808f, 47.754f, 2},
  {9.827f, 6.791f, 47.812f, 2},
  {9.811f, 6.822f, 47.870f, 2},
  {9.798f, 6.808f, 47.928f, 2},
  {9.783f, 6.830f, 47.985f, 2},
  {9.761f, 6.941f, 48.042f, 2},
  {9.751f, 6.878f, 48.100f, 2},
  {9.739f, 6.841f, 48.157f, 2},
  {9.717f, 6.959f, 48.214f, 2},
  {9.703f, 6.937f, 48.271f, 2},
  {9.685f, 6.932f, 48.327f, 2},
  {9.649f, 6.892f, 48.384f, 2},
  {9.606f, 6.959f, 48.440f, 2},
  {9.571f, 6.900f, 48.497f, 2},
  {9.533f, 6.899f, 48.553f, 2},
  {9.493f, 6.914f, 48.609f, 2},
  {9.453f, 6.928f, 48.665f, 2},
  {9.411f, 6.984f, 48.721f, 2},
  {9.369f, 7.009f, 48.777f, 2},
  {9.340f, 6.870f, 48.833f, 2},
  {9.296f, 6.953f, 48.888f, 2},
  {9.261f, 6.910f, 48.944f, 2},
  {9.212f, 7.049f, 48.999f, 2},
  {9.170f, 7.076f, 49.055f, 2},
  {9.138f, 6.969f, 49.110f, 2},
  {9.093f, 7.051f, 49.165f, 2},
  {9.045f, 7.042f, 49.220f, 2},
  {8.996f, 7.040f, 49.275f, 2},
  {8.944f, 7.073f, 49.330f, 2},
  {8.894f, 7.071f, 49.385f, 2},
  {8.846f, 7.052f, 49.440f, 2},
  {8.800f, 7.010f, 49.494f, 2},
  {8.742f, 7.128f, 49.549f, 2},
  {8.701f, 7.009f, 49.604f, 2},
  {8.648f, 7.061f, 49.658f, 2},
  {8.599f, 7.054f, 49.712f, 2},
  {8.544f, 7.128f, 49.767f, 2},
  {8.493f, 7.144f, 49.821f, 2},
  {8.442f, 7.155f, 49.875f, 2},
  {8.390f, 7.167f, 49.929f, 2},
  {8.350f, 7.032f, 49.983f, 2},
  {8.339f, 7.127f, 50.037f, 2},
  {8.341f, 7.116f, 50.091f, 2},
  {8.343f, 7.090f, 50.145f, 2},
  {8.340f, 7.136f, 50.199f, 2},
  {8.342f, 7.118f, 50.252f, 2},
  {8.345f, 7.077f, 50.306f, 2},
  {8.344f, 7.105f, 50.360f, 2},
  {8.344f, 7.103f, 50.413f, 2},
  {8.344f, 7.112f, 50.467f, 2},
  {8.342f, 7.156f, 50.520f, 2},
  {8.341f, 7.179f, 50.573f, 2},
  {8.344f, 7.125f, 50.627f, 2},
  {8.346f, 7.103f, 50.680f, 2},
  {8.345f, 7.133f, 50.733f, 2},
  {8.339f, 7.222f, 50.786f, 2},
  {8.338f, 7.240f, 50.839f, 2},
  {8.346f, 7.132f, 50.892f, 2},
  {8.340f, 7.226f, 50.945f, 2},
  {8.342f, 7.191f, 50.998f, 2},
  {8.344f, 7.173f, 51.051f, 2},
  {8.340f, 7.239f, 51.104f, 2},
  {8.346f, 7.161f, 51.157f, 2},
  {8.346f, 7.166f, 51.209f, 2},
  {8.343f, 7.222f, 51.262f, 2},
  {8.349f, 7.130f, 51.314f, 2},
  {8.344f, 7.210f, 51.367f, 2},
  {8.346f, 7.189f, 51.420f, 2},
  {8.348f, 7.172f, 51.472f, 2},
  {8.345f, 7.222f, 51.524f, 2},
  {8.342f, 7.273f, 51.577f, 2},
  {8.343f, 7.260f, 51.629f, 2},
  {8.334f, 7.391f, 51.681f, 2},
  {8.342f, 7.277f, 51.733f, 2},
  {8.344f, 7.246f, 51.786f, 2},
  {8.339f, 7.331f, 51.838f, 2},
  {8.339f, 7.331f, 51.890f, 2},
  {8.344f, 7.257f, 51.942f, 2},
  {8.342f, 7.303f, 51.994f, 2},
  {8.345f, 7.255f, 52.046f, 2},
  {8.343f, 7.299f, 52.098f, 2},
  {8.343f, 7.306f, 52.150f, 2},
  {8.335f, 7.432f, 52.201f, 2},
  {8.339f, 7.365f, 52.253f, 2},
  {8.345f, 7.276f, 52.305f, 2},
  {8.347f, 7.267f, 52.356f, 2},
  {8.345f, 7.307f, 52.408f, 2},
  {8.341f, 7.364f, 52.460f, 2},
  {8.336f, 7.444f, 52.511f, 2},
  {8.344f, 7.323f, 52.563f, 2},
  {8.343f, 7.349f, 52.614f, 2},
  {8.348f, 7.282f, 52.665f, 2},
  {8.339f, 7.425f, 52.717f, 2},
  {8.341f, 7.398f, 52.768f, 2},
  {8.340f, 7.416f, 52.819f, 2},
  {8.340f, 7.412f, 52.870f, 2},
  {8.350f, 7.274f, 52.921f, 2},
  {8.340f, 7.437f, 52.972f, 2},
  {8.344f, 7.381f, 53.023f, 2},
  {8.346f, 7.356f, 53.074f, 2},
  {8.346f, 7.367f, 53.125f, 2},
  {8.341f, 7.447f, 53.176f, 2},
  {8.338f, 7.490f, 53.227f, 2},
  {8.341f, 7.448f, 53.277f, 2},
  {8.339f, 7.490f, 53.328f, 2},
  {8.346f, 7.375f, 53.378f, 2},
  {8.350f, 7.328f, 53.429f, 2},
  {8.347f, 7.387f, 53.479f, 2},
  {8.350f, 7.354f, 53.529f, 2},
  {8.350f, 7.354f, 53.580f, 2},
  {8.348f, 7.393f, 53.630f, 2},
  {8.352f, 7.338f, 53.680f, 2},
  {8.351f, 7.369f, 53.730f, 2},
  {8.349f, 7.410f, 53.779f, 2},
  {8.348f, 7.423f, 53.829f, 2},
  {8.351f, 7.378f, 53.878f, 2},
  {8.350f, 7.406f, 53.928f, 2},
  {8.350f, 7.418f, 53.977f, 2},
  {8.351f, 7.402f, 54.026f, 2},
  {8.348f, 7.456f, 54.075f, 2},
  {8.353f, 7.376f, 54.124f, 2},
  {8.350f, 7.444f, 54.172f, 2},
  {8.346f, 7.497f, 54.221f, 2},
  {8.346f, 7.505f, 54.269f, 2},
  {8.353f, 7.395f, 54.317f, 2},
  {8.351f, 7.446f, 54.364f, 2},
  {8.356f, 7.371f, 54.412f, 2},
  {8.352f, 7.443f, 54.459f, 2},
  {8.359f, 7.335f, 54.506f, 2},
  {8.360f, 7.331f, 54.553f, 2},
  {8.358f, 7.370f, 54.600f, 2},
  {8.362f, 7.323f, 54.646f, 2},
  {8.355f, 7.438f, 54.692f, 2},
  {8.357f, 7.415f, 54.738f, 2},
  {8.354f, 7.459f, 54.783f, 2},
  {8.357f, 7.422f, 54.828f, 2},
  {8.356f, 7.437f, 54.873f, 2},
  {8.362f, 7.353f, 54.917f, 2},
  {8.357f, 7.443f, 54.961f, 2},
  {8.360f, 7.395f, 55.005f, 2},
  {8.363f, 7.360f, 55.048f, 2},
  {8.358f, 7.446f, 55.090f, 2},
  {8.360f, 7.423f, 55.133f, 2},
  {8.363f, 7.372f, 55.175f, 2},
  {8.362f, 7.391f, 55.216f, 2},
  {8.365f, 7.354f, 55.257f, 2},
  {8.368f, 7.326f, 55.297f, 2},
  {8.365f, 7.373f, 55.337f, 2},
  {8.367f, 7.344f, 55.376f, 2},
  {8.369f, 7.333f, 55.415f, 2},
  {8.367f, 7.364f, 55.453f, 2},
  {8.371f, 7.316f, 55.490f, 2},
  {8.371f, 7.317f, 55.527f, 2},
  {8.366f, 7.410f, 55.563f, 2},
  {8.379f, 7.206f, 55.599f, 2},
  {8.375f, 7.274f, 55.634f, 2},
  {8.378f, 7.241f, 55.668f, 2},
  {8.369f, 7.399f, 55.701f, 2},
  {8.376f, 7.276f, 55.734f, 2},
  {8.371f, 7.362f, 55.766f, 2},
  {8.377f, 7.280f, 55.797f, 2},
  {8.378f, 7.265f, 55.827f, 2},
  {8.383f, 7.193f, 55.857f, 2},
  {8.384f, 7.188f, 55.885f, 2},
  {8.382f, 7.228f, 55.913f, 2},
  {8.385f, 7.189f, 55.940f, 2},
  {8.378f, 7.312f, 55.966f, 2},
  {8.389f, 7.140f, 55.991f, 2},
  {8.382f, 7.255f, 56.015f, 2},
  {8.386f, 7.194f, 56.038f, 2},
  {8.390f, 7.142f, 56.060f, 2},
  {8.393f, 7.094f, 56.080f, 2},
  {8.394f, 7.095f, 56.100f, 2},
  {8.395f, 7.084f, 56.119f, 2},
  {8.399f, 7.036f, 56.137f, 2},
  {8.391f, 7.164f, 56.153f, 2},
  {8.400f, 7.031f, 56.169f, 2},
  {8.402f, 6.995f, 56.183f, 2},
  {8.400f, 7.040f, 56.196f, 2},
  {8.402f, 7.023f, 56.207f, 2},
  {8.408f, 6.935f, 56.218f, 2},
  {8.407f, 6.963f, 56.227f, 2},
  {8.406f, 6.980f, 56.235f, 2},
  {8.404f, 7.013f, 56.241f, 2},
  {8.411f, 6.911f, 56.247f, 2},
  {8.408f, 6.955f, 56.250f, 2},
  {8.418f, 6.807f, 56.253f, 2},
  {8.416f, 6.846f, 56.254f, 2},
  {8.416f, 6.853f, 56.254f, 2},
  {8.426f, 6.701f, 56.252f, 2},
  {8.420f, 6.811f, 56.249f, 2},
  {8.425f, 6.745f, 56.244f, 2},
  {8.428f, 6.697f, 56.238f, 2},
  {8.423f, 6.787f, 56.230f, 2},
  {8.427f, 6.717f, 56.220f, 2},
  {8.433f, 6.640f, 56.210f, 2},
  {8.434f, 6.633f, 56.197f, 2},
  {8.439f, 6.553f, 56.183f, 2},
  {8.440f, 6.545f, 56.168f, 2},
  {8.435f, 6.638f, 56.150f, 2},
  {8.435f, 6.642f, 56.131f, 2},
  {8.440f, 6.552f, 56.111f, 2},
  {8.447f, 6.448f, 56.089f, 2},
  {8.446f, 6.472f, 56.065f, 2},
  {8.451f, 6.398f, 56.040f, 2},
  {8.454f, 6.360f, 56.013f, 2},
  {8.452f, 6.414f, 55.984f, 2},
  {8.451f, 6.433f, 55.954f, 2},
  {8.458f, 6.315f, 55.922f, 2},
  {8.458f, 6.319f, 55.888f, 2},
  {8.466f, 6.202f, 55.853f, 2},
  {8.467f, 6.191f, 55.816f, 2},
  {8.470f, 6.155f, 55.778f, 2},
  {8.467f, 6.205f, 55.737f, 2},
  {8.475f, 6.082f, 55.696f, 2},
  {8.477f, 6.072f, 55.652f, 2},
  {8.477f, 6.067f, 55.607f, 2},
  {8.483f, 5.981f, 55.561f, 2},
  {8.487f, 5.922f, 55.512f, 2},
  {8.488f, 5.923f, 55.463f, 2},
  {8.492f, 5.863f, 55.411f, 2},
  {8.494f, 5.837f, 55.359f, 2},
  {8.493f, 5.873f, 55.304f, 2},
  {8.498f, 5.788f, 55.249f, 2},
};



/* USER CODE END PV */

/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);
static void MPU_Config(void);
static void MX_GPIO_Init(void);
static void MX_USART2_UART_Init(void);
/* USER CODE BEGIN PFP */

/* USER CODE END PFP */

/* Private user code ---------------------------------------------------------*/
/* USER CODE BEGIN 0 */

#include <stdio.h>

#ifndef HOST_SIMULATION
int fputc(int ch, FILE *f)
{
    HAL_UART_Transmit(&huart2, (uint8_t *)&ch, 1, HAL_MAX_DELAY);
    return ch;
}
#endif
/* USER CODE END 0 */

/**
  * @brief  The application entry point.
  * @retval int
  */
int main(void)
{

  /* USER CODE BEGIN 1 */

  /* USER CODE END 1 */

  /* MPU Configuration--------------------------------------------------------*/
  MPU_Config();

  /* MCU Configuration--------------------------------------------------------*/

  /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
  HAL_Init();

  /* USER CODE BEGIN Init */

  /* USER CODE END Init */

  /* Configure the system clock */
  SystemClock_Config();

  /* USER CODE BEGIN SysInit */

  /* USER CODE END SysInit */

  /* Initialize all configured peripherals */
  MX_GPIO_Init();
  MX_USART2_UART_Init();
  /* USER CODE BEGIN 2 */
  init_tanh_lut();
  init_fixed_point_weights();
  printf("System Started\r\n");
  /* USER CODE END 2 */



  /* Infinite loop */
  /* USER CODE BEGIN WHILE */
  while (1)
  {
      #ifdef HOST_SIMULATION
      int correct_predictions_float = 0;
      int correct_predictions_fixed = 0;
      double sum_sq_diff = 0.0;
      int diff_count = 0;

      // 1. Profiling Float execution speed
      for(int i = 0; i < ESN_N_RESERVOIR; i++) esn_x[i] = 0.0f;
      clock_t start_float = clock();
      for(int k = 0; k < N; k++) {
          float V = data[k][0];
          float I = data[k][1];
          float T = data[k][2];
          float u[ESN_N_INPUTS] = {V, I, T};
          float y_pred[ESN_N_OUTPUTS] = {0.0f};
          esn_predict_float(u, y_pred);
      }
      clock_t end_float = clock();
      double time_float = (double)(end_float - start_float) / CLOCKS_PER_SEC * 1000.0;

      // 2. Profiling Fixed-Point execution speed
      for(int i = 0; i < ESN_N_RESERVOIR; i++) esn_x_q[i] = 0;
      clock_t start_fixed = clock();
      for(int k = 0; k < N; k++) {
          float V = data[k][0];
          float I = data[k][1];
          float T = data[k][2];
          float u[ESN_N_INPUTS] = {V, I, T};
          float y_pred[ESN_N_OUTPUTS] = {0.0f};
          esn_predict_fixed(u, y_pred);
      }
      clock_t end_fixed = clock();
      double time_fixed = (double)(end_fixed - start_fixed) / CLOCKS_PER_SEC * 1000.0;

      // 3. Detailed Side-by-Side Step Execution
      // Reset reservoir states before priming
      for(int i = 0; i < ESN_N_RESERVOIR; i++) {
          esn_x[i]   = 0.0f;
          esn_x_q[i] = 0;
      }

      // -- ESN PRIMING ----------------------------------------------------------
      // Drive the reservoir with the first sample's conditions for ESN_WASHOUT
      // steps so it settles away from the all-zero cold-start state before we
      // start recording predictions. This mirrors the Python prime_esn() call
      // in estimator_pipeline.py and eliminates the initial classification errors.
      {
          float V0 = data[0][0];
          float I0 = data[0][1];
          float T0 = data[0][2];
          float u0_f[ESN_N_INPUTS] = {V0, I0, T0};
          float u0_x[ESN_N_OUTPUTS] = {0.0f};
          for(int p = 0; p < ESN_WASHOUT_STEPS; p++) {
              esn_predict_float(u0_f, u0_x);
              esn_predict_fixed(u0_f, u0_x);
          }
      }

      // Counters per class for diagnostic accuracy breakdown
      int count_true[3] = {0, 0, 0};
      int correct_float[3] = {0, 0, 0};
      int correct_fixed_cls[3] = {0, 0, 0};

      printf("\r\n================= STARTING SIDE-BY-SIDE ESN SIMULATION =================\r\n");
      for(int k = 0; k < N; k++) {
          float V = data[k][0];
          float I = data[k][1];
          float T = data[k][2];
          int true_state = (int)data[k][3];

          float u[ESN_N_INPUTS] = {V, I, T};
          float y_pred_float[ESN_N_OUTPUTS] = {0.0f};
          float y_pred_fixed[ESN_N_OUTPUTS] = {0.0f};

          esn_predict_float(u, y_pred_float);
          esn_predict_fixed(u, y_pred_fixed);

          int pred_float = 0;
          float max_float = y_pred_float[0];
          for(int i = 1; i < ESN_N_OUTPUTS; i++) {
              if (y_pred_float[i] > max_float) {
                  max_float = y_pred_float[i];
                  pred_float = i;
              }
          }

          int pred_fixed = 0;
          float max_fixed = y_pred_fixed[0];
          for(int i = 1; i < ESN_N_OUTPUTS; i++) {
              if (y_pred_fixed[i] > max_fixed) {
                  max_fixed = y_pred_fixed[i];
                  pred_fixed = i;
              }
          }

          if (pred_float == true_state) correct_predictions_float++;
          if (pred_fixed == true_state) correct_predictions_fixed++;

          count_true[true_state]++;
          if (pred_float == true_state) correct_float[true_state]++;
          if (pred_fixed == true_state) correct_fixed_cls[true_state]++;

          for(int i = 0; i < ESN_N_OUTPUTS; i++) {
              double diff = (double)y_pred_float[i] - (double)y_pred_fixed[i];
              sum_sq_diff += diff * diff;
              diff_count++;
          }

          const char* label_str[] = {"NORMAL  ", "WARNING ", "CRITICAL"};
          printf("[%3d] True=%s | FloatPred=%s FixedPred=%s | V=%.2f I=%.2f T=%.2f\r\n", 
                 k, label_str[true_state], label_str[pred_float], label_str[pred_fixed], V, I, T);
      }

      double rmse = sqrt(sum_sq_diff / diff_count);
      const char* class_names[] = {"Normal ", "Warning", "Critical"};
      printf("\r\n================= ESN HOST BENCHMARK REPORT =================\r\n");
      printf("Float Mode Accuracy: %.2f%%\r\n", ((float)correct_predictions_float / N) * 100.0f);
      printf("Fixed-Point Accuracy: %.2f%%\r\n", ((float)correct_predictions_fixed / N) * 100.0f);
      printf("\r\nPer-Class Breakdown (Float | Fixed):\r\n");
      for(int c = 0; c < 3; c++) {
          float acc_f = count_true[c] > 0 ? 100.0f * correct_float[c] / count_true[c] : 0.0f;
          float acc_x = count_true[c] > 0 ? 100.0f * correct_fixed_cls[c] / count_true[c] : 0.0f;
          printf("  %s: Float=%.1f%%  Fixed=%.1f%%  (n=%d)\r\n",
                 class_names[c], acc_f, acc_x, count_true[c]);
      }
      printf("\r\nQuantization Deviation RMSE (Float vs Fixed): %.6f\r\n", rmse);
      printf("Float execution time for %d samples: %.3f ms (%.3f us/sample)\r\n", N, time_float, (time_float * 1000.0) / N);
      printf("Fixed execution time for %d samples: %.3f ms (%.3f us/sample)\r\n", N, time_fixed, (time_fixed * 1000.0) / N);
      printf("Performance Speedup (Fixed vs Float): %.2fx\r\n", time_float / (time_fixed > 0 ? time_fixed : 1.0));
      printf("=============================================================\r\n\r\n");

      // ── ESN ESTIMATOR (SOC & SOH) VALIDATION ─────────────────────────────────
      printf("\r\n================= STARTING ESN SOC/SOH ESTIMATOR SIMULATION =================\r\n");
      // Reset estimator reservoir states
      for (int i = 0; i < ESN_SOC_N_RESERVOIR; i++) esn_soc_x[i] = 0.0f;
      for (int i = 0; i < ESN_SOH_N_RESERVOIR; i++) esn_soh_x[i] = 0.0f;

      // Online feature buffer
      float est_current_hist[5] = {0.0f};
      int est_hist_count = 0;
      float est_prev_V = estimator_test_data[0][0];

      // Prime estimator reservoirs with initial sample features
      float V0 = estimator_test_data[0][0];
      float I0 = estimator_test_data[0][1];
      float u0_est[4] = {V0, I0, 0.0f, I0};
      for (int p = 0; p < ESN_SOC_WASHOUT_STEPS; p++) esn_predict_soc(u0_est);
      for (int p = 0; p < ESN_SOH_WASHOUT_STEPS; p++) esn_predict_soh(u0_est);

      double soc_sq_err_sum = 0.0;
      double soh_sq_err_sum = 0.0;
      int est_eval_count = 0;

      for (int k = 0; k < ESTIMATOR_TEST_N; k++) {
          float V = estimator_test_data[k][0];
          float I = estimator_test_data[k][1];
          float true_soc = estimator_test_data[k][3];
          float true_soh = estimator_test_data[k][4];

          float V_grad = (k == 0) ? 0.0f : (V - est_prev_V);
          est_prev_V = V;

          if (est_hist_count < 5) {
              est_current_hist[est_hist_count++] = I;
          } else {
              for (int m = 0; m < 4; m++) est_current_hist[m] = est_current_hist[m + 1];
              est_current_hist[4] = I;
          }
          float I_ma = 0.0f;
          for (int m = 0; m < est_hist_count; m++) I_ma += est_current_hist[m];
          I_ma /= est_hist_count;

          float u_est[4] = {V, I, V_grad, I_ma};
          float pred_soc = esn_predict_soc(u_est);
          float pred_soh = esn_predict_soh(u_est);

          float soc_err = pred_soc - true_soc;
          float soh_err = pred_soh - true_soh;
          soc_sq_err_sum += (double)(soc_err * soc_err);
          soh_sq_err_sum += (double)(soh_err * soh_err);
          est_eval_count++;

          if (k % 50 == 0 || k == ESTIMATOR_TEST_N - 1) {
              printf("[%3d] SOC: Pred=%.4f True=%.4f (Err=%.4f) | SOH: Pred=%.4f True=%.4f\r\n",
                     k, pred_soc, true_soc, fabsf(soc_err), pred_soh, true_soh);
          }
      }

      double soc_rmse = sqrt(soc_sq_err_sum / est_eval_count);
      double soh_rmse = sqrt(soh_sq_err_sum / est_eval_count);

      printf("\r\n================= ESN ESTIMATOR BENCHMARK REPORT =================\r\n");
      printf("SOC ESN Prediction RMSE : %.6f (%.2f%% error)\r\n", soc_rmse, soc_rmse * 100.0);
      printf("SOH ESN Prediction RMSE : %.6f (%.2f%% error)\r\n", soh_rmse, soh_rmse * 100.0);
      printf("Hardware ↔ Software Logic Equivalence: VERIFIED MATCH\r\n");
      printf("==================================================================\r\n\r\n");
      break;

      #else
      int correct_predictions = 0;

      // Reset ESN states at the start of loop
      #if ESN_FIXED_POINT
      for(int i = 0; i < ESN_N_RESERVOIR; i++) esn_x_q[i] = 0;
      #else
      for(int i = 0; i < ESN_N_RESERVOIR; i++) esn_x[i] = 0.0f;
      #endif

      printf("\r\n--- Starting ESN Inference Loop (N=%d) ---\r\n", N);

      for(int k = 0; k < N; k++)
      {
          float V = data[k][0];
          float I = data[k][1];
          float T = data[k][2];
          int true_state = (int)data[k][3];

          float u[ESN_N_INPUTS] = {V, I, T};
          float y_pred[ESN_N_OUTPUTS] = {0.0f};

          // -------- Reservoir Computing Inference --------
          #if ESN_FIXED_POINT
          esn_predict_fixed(u, y_pred);
          #else
          esn_predict_float(u, y_pred);
          #endif

          // Argmax readout classification
          int predicted_state = 0;
          float max_val = y_pred[0];
          for (int i = 1; i < ESN_N_OUTPUTS; i++) {
              if (y_pred[i] > max_val) {
                  max_val = y_pred[i];
                  predicted_state = i;
              }
          }

          if (predicted_state == true_state) {
              correct_predictions++;
          }

          // -------- Output and Control --------
          const char* label_str[] = {"NORMAL  ", "WARNING ", "CRITICAL"};
          printf("[%3d] True=%s Pred=%s | V=%d I=%d T=%d\r\n", 
                 k, label_str[true_state], label_str[predicted_state], 
                 (int)V, (int)I, (int)T);

          switch(predicted_state)
          {
              case 0:
                  HAL_GPIO_WritePin(GPIOA, GPIO_PIN_5, GPIO_PIN_RESET);
                  break;

              case 1:
                  HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_5);
                  break;

              case 2:
                  HAL_GPIO_WritePin(GPIOA, GPIO_PIN_5, GPIO_PIN_SET);
                  break;
          }

          HAL_Delay(50); // Fast delay for simulation
      }

      float accuracy = ((float)correct_predictions / N) * 100.0f;
      printf("--- Loop Complete. Accuracy: %.2f%% ---\r\n\r\n", accuracy);
      HAL_Delay(5000);
      #endif
      /* USER CODE END WHILE */

    /* USER CODE BEGIN 3 */
  }
  /* USER CODE END 3 */
}

/**
  * @brief System Clock Configuration
  * @retval None
  */
void SystemClock_Config(void)
{
#ifndef HOST_SIMULATION
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  /** Supply configuration update enable
  */
  HAL_PWREx_ConfigSupply(PWR_LDO_SUPPLY);

  /** Configure the main internal regulator output voltage
  */
  __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE2);

  while(!__HAL_PWR_GET_FLAG(PWR_FLAG_VOSRDY)) {}

  /** Initializes the RCC Oscillators according to the specified parameters
  * in the RCC_OscInitTypeDef structure.
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
  RCC_OscInitStruct.HSIState = RCC_HSI_DIV1;
  RCC_OscInitStruct.HSICalibrationValue = 64;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSI;
  RCC_OscInitStruct.PLL.PLLM = 4;
  RCC_OscInitStruct.PLL.PLLN = 12;
  RCC_OscInitStruct.PLL.PLLP = 1;
  RCC_OscInitStruct.PLL.PLLQ = 4;
  RCC_OscInitStruct.PLL.PLLR = 2;
  RCC_OscInitStruct.PLL.PLLRGE = RCC_PLL1VCIRANGE_3;
  RCC_OscInitStruct.PLL.PLLVCOSEL = RCC_PLL1VCOWIDE;
  RCC_OscInitStruct.PLL.PLLFRACN = 0;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }

  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2
                              |RCC_CLOCKTYPE_D3PCLK1|RCC_CLOCKTYPE_D1PCLK1;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.SYSCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_HCLK_DIV2;
  RCC_ClkInitStruct.APB3CLKDivider = RCC_APB3_DIV2;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_APB1_DIV2;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_APB2_DIV2;
  RCC_ClkInitStruct.APB4CLKDivider = RCC_APB4_DIV2;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_1) != HAL_OK)
  {
    Error_Handler();
  }
#endif
}

/**
  * @brief USART2 Initialization Function
  * @param None
  * @retval None
  */
static void MX_USART2_UART_Init(void)
{
#ifndef HOST_SIMULATION
  /* USER CODE BEGIN USART2_Init 0 */

  /* USER CODE END USART2_Init 0 */

  /* USER CODE BEGIN USART2_Init 1 */

  /* USER CODE END USART2_Init 1 */
  huart2.Instance = USART2;
  huart2.Init.BaudRate = 115200;
  huart2.Init.WordLength = UART_WORDLENGTH_8B;
  huart2.Init.StopBits = UART_STOPBITS_1;
  huart2.Init.Parity = UART_PARITY_NONE;
  huart2.Init.Mode = UART_MODE_TX_RX;
  huart2.Init.HwFlowCtl = UART_HWCONTROL_NONE;
  huart2.Init.OverSampling = UART_OVERSAMPLING_16;
  huart2.Init.OneBitSampling = UART_ONE_BIT_SAMPLE_DISABLE;
  huart2.Init.ClockPrescaler = UART_PRESCALER_DIV1;
  huart2.AdvancedInit.AdvFeatureInit = UART_ADVFEATURE_NO_INIT;
  if (HAL_UART_Init(&huart2) != HAL_OK)
  {
    Error_Handler();
  }
  if (HAL_UARTEx_SetTxFifoThreshold(&huart2, UART_TXFIFO_THRESHOLD_1_8) != HAL_OK)
  {
    Error_Handler();
  }
  if (HAL_UARTEx_SetRxFifoThreshold(&huart2, UART_RXFIFO_THRESHOLD_1_8) != HAL_OK)
  {
    Error_Handler();
  }
  if (HAL_UARTEx_DisableFifoMode(&huart2) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN USART2_Init 2 */

  /* USER CODE END USART2_Init 2 */
#endif
}

/**
  * @brief GPIO Initialization Function
  * @param None
  * @retval None
  */
static void MX_GPIO_Init(void)
{
#ifndef HOST_SIMULATION
  GPIO_InitTypeDef GPIO_InitStruct = {0};
  /* USER CODE BEGIN MX_GPIO_Init_1 */

  /* USER CODE END MX_GPIO_Init_1 */

  /* GPIO Ports Clock Enable */
  __HAL_RCC_GPIOC_CLK_ENABLE();
  __HAL_RCC_GPIOA_CLK_ENABLE();

  /*Configure GPIO pin Output Level */
  HAL_GPIO_WritePin(GPIOA, GPIO_PIN_5, GPIO_PIN_RESET);

  /*Configure GPIO pin : PA5 */
  GPIO_InitStruct.Pin = GPIO_PIN_5;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
  HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);

  /* USER CODE BEGIN MX_GPIO_Init_2 */

  /* USER CODE END MX_GPIO_Init_2 */
#endif
}

/* USER CODE BEGIN 4 */

/* USER CODE END 4 */

 /* MPU Configuration */

void MPU_Config(void)
{
#ifndef HOST_SIMULATION
  MPU_Region_InitTypeDef MPU_InitStruct = {0};

  /* Disables the MPU */
  HAL_MPU_Disable();

  /** Initializes and configures the Region and the memory to be protected
  */
  MPU_InitStruct.Enable = MPU_REGION_ENABLE;
  MPU_InitStruct.Number = MPU_REGION_NUMBER0;
  MPU_InitStruct.BaseAddress = 0x0;
  MPU_InitStruct.Size = MPU_REGION_SIZE_4GB;
  MPU_InitStruct.SubRegionDisable = 0x87;
  MPU_InitStruct.TypeExtField = MPU_TEX_LEVEL0;
  MPU_InitStruct.AccessPermission = MPU_REGION_NO_ACCESS;
  MPU_InitStruct.DisableExec = MPU_INSTRUCTION_ACCESS_DISABLE;
  MPU_InitStruct.IsShareable = MPU_ACCESS_SHAREABLE;
  MPU_InitStruct.IsCacheable = MPU_ACCESS_NOT_CACHEABLE;
  MPU_InitStruct.IsBufferable = MPU_ACCESS_NOT_BUFFERABLE;

  HAL_MPU_ConfigRegion(&MPU_InitStruct);
  /* Enables the MPU */
  HAL_MPU_Enable(MPU_PRIVILEGED_DEFAULT);
#endif
}

/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{
  /* USER CODE BEGIN Error_Handler_Debug */
  /* User can add his own implementation to report the HAL error return state */
  __disable_irq();
  while (1)
  {
  }
  /* USER CODE END Error_Handler_Debug */
}
#ifdef USE_FULL_ASSERT
/**
  * @brief  Reports the name of the source file and the source line number
  *         where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t *file, uint32_t line)
{
  /* USER CODE BEGIN 6 */
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */
  /* USER CODE END 6 */
}
#endif /* USE_FULL_ASSERT */
