`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Module Name: address_generator
//
// Revision:
// Revision 0.01 - File Created
// Revision 0.02 - Reviewed for the full-design bug sweep: purely
//                 combinational base-address generation, no registers,
//                 no FSM. No logic bug found.
// Revision 0.03 - Removed the x_addr (input) / x_mem_addr (output)
//                 ports. These were leftover from before esn_top.v
//                 existed. Once esn_top.v was reviewed, its own rev
//                 0.09 note made clear the intent: x_addr is solely
//                 owned/generated by esn_neuron (x_addr <= res_count;
//                 in S_W_ADDR, mirroring w_addr) and wired directly
//                 to both state_bram read ports -- address_generator
//                 was never meant to touch it. esn_top's instantiation
//                 of this module only connects .neuron_idx,
//                 .win_base_addr, .w_base_addr; it never connects
//                 x_addr/x_mem_addr. Leaving those two ports declared
//                 here didn't cause a functional bug (unconnected
//                 Verilog ports simply float/dangle), but it left this
//                 module's port list inconsistent with how esn_top
//                 actually instantiates it and with rev 0.09's stated
//                 intent. This module now only generates the two
//                 per-neuron BASE addresses, matching esn_top exactly.
// Additional Comments:
//
//////////////////////////////////////////////////////////////////////////////////
module address_generator
#(
    parameter N_IN  = 4,
    parameter N_RES = 100
)
(
    //----------------------------------------------------------
    // Current Neuron
    //----------------------------------------------------------
    input  wire [$clog2(N_RES)-1:0] neuron_idx,
    //----------------------------------------------------------
    // Base Address Outputs
    //----------------------------------------------------------
    output wire [$clog2(N_IN*N_RES)-1:0]  win_base_addr,
    output wire [$clog2(N_RES*N_RES)-1:0] w_base_addr
);
////////////////////////////////////////////////////////////
// Base Address Generation
////////////////////////////////////////////////////////////
assign win_base_addr = neuron_idx * N_IN;
assign w_base_addr   = neuron_idx * N_RES;
endmodule
